name: get package for truenas scale

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/get_package.yaml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.2'
      - name: get package
        run: |
          cd $GITHUB_WORKSPACE
          python --version
          pip --version
          rm -rf package/
          pip install -r requirements.txt -t package/
          cd package
          tar zcvf package.tar.gz *
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package.tar.gz
          path: ./package.tar.gz